### ISSUE TITLE
Datetime axis interval incorrect

### ISSUE THREAD

**Issue by Grumium** [nline/nline-plotlyjs-panel#1]
The following simple code diplays a time series in an interval pre-defined by the built-in variables `variables.__from,`and `variables.__to`.

```
let x = data.series[0].fields[0].values.buffer;
let y = data.series[0].fields[1].values.buffer;

let series = {
  x: x,
  y: y,
};
var layout ={
  xaxis: {
    automargin: false,
    autorange: false,
    range: [variables.__from,variables.__to],
    type: 'linear',
  },  
}
return {
  data: [series],
  layout: layout,
};
```

Result:
![Screenshot from 2023-01-23 13-18-00](https://user-images.githubusercontent.com/47479352/214038000-d0140c60-3452-4c13-8484-33de7078a386.png)

However, the datetime axis is not formatted properly, since it has the wrong type.

**Two problems:** 

- When changing the type to `type: 'date'`, the range is not displayed correctly.

![Screenshot from 2023-01-23 13-25-55](https://user-images.githubusercontent.com/47479352/214039738-828d7dec-d2b5-4ddf-93a3-5e23e2b16b2c.png)

- When setting the xaxis to `autorange: true`, the interval is set to the range of available data, ignoring the interval defined by Grafana.

![Screenshot from 2023-01-23 13-26-05](https://user-images.githubusercontent.com/47479352/214039552-567da6e4-8e9e-498b-9401-6106a589b0c8.png)

Thanks for looking into this.

**Comment by jacksongoode** [comment]
Hi @Grumium thanks for bringing this up. It is an interesting case. So typically the data range is defined by Grafana's time filter, if you filter your query by time. You're not using a random walk of data are you? Could I see the query that you're using in this example?

**Comment by jacksongoode** [comment]
However, just thinking about this, I think the issue you have is that the variables `variables.__from` and `variables.__to` are actually integers and might need to be interpreted as date objects for you to manually set the intervals _and_ get the proper formatting.

**Comment by jacksongoode** [comment]
@Grumium I'm going to close this unless you're continuing to have an issue - let me know.
