### ISSUE TITLE
1.3.0 to 1.5.0 breaks (some) subplot functionality 

### ISSUE THREAD

**Issue by b-neufeld** [nline/nline-plotlyjs-panel#13]
I've got a kludge of a plot that's a 2-high by 6-wide array of subplots. 

I updated from 1.3.0 to 1.5.0 and the bar plot circled in the image below (subplot "xy" in the attached code) was missing entirely, with a 1969 timestamp appearing on the x-axis label, below where the chart should be.
![image](https://github.com/nline/nline-plotlyjs-panel/assets/18536548/2609ece1-d22c-4bd1-9e3a-8a5f7f3c78c4)

I should have taken a screenshot of the behaviour, but I reverted versions too quick. 

It's something to do with subplot "xy", possibly confusing because the bottom row of gauges are positioned by "domain" and the top row of mixed bar charts/box plots are positioned by assigning to xaxis/yaxis. The fact that the 1969 timestamp showed up on the top-left bar chart's x-axis label makes me wonder if something between Grafana and Plotly is expecting a timestamp (whereas I've stripped all timestamps from the data feeding the bar chart and box plots). 

I won't want to make anyone figure out my crappy code, this is not a dealbreaker for me as I can just stay on 1.3.0, just like to share when things act funny, but maybe there is a quick fix based on known changes. 

Panel JSON, panel data, and dataframe json attached:
[panel_json.txt](https://github.com/nline/nline-plotlyjs-panel/files/12235344/panel_json.txt)
[panel_data.txt](https://github.com/nline/nline-plotlyjs-panel/files/12235345/panel_data.txt)
[dataframe_json.txt](https://github.com/nline/nline-plotlyjs-panel/files/12235346/dataframe_json.txt)

If I take another run at upgrading I'll report back here if I can figure it out.

**Comment by jacksongoode** [comment]
It worth seeing the defaults we use in the panel, when there are no props specified to override. https://github.com/nline/nline-plotlyjs-panel/blob/3d732a0f76f742c6a193a3dabce4f45639c69d3c/src/types.ts#L30C20-L30C20 My guess is that the default is `xaxis: type: "date"` which maybe you need to specify to "category" is my guess.

**Comment by jacksongoode** [comment]
@b-neufeld Just want to check in to see if the above resolved for you?

**Comment by b-neufeld** [comment]
Yeah, that was it. Thanks @jacksongoode, appreciate the reply and thanks for following up! I love easy fixes. Was just hard to spot "in the moment" after an update.
