### ISSUE TITLE
Import JavaScript library

### ISSUE THREAD

**Issue by SBS-EREHM** [nline/nline-plotlyjs-panel#14]
What is the best way to import a JS Library to use in the Script part?

In my case, I want to do some numpy-like array math using the npm package [@dc4/numjs](https://www.npmjs.com/package/@d4c/numjs )

**Comment by jacksongoode** [comment]
This is out of the scope of features for the plugin, but I imagine you can load it through a script tag? You might have to fiddle with this:

```js
(function() {
  if (!window.nj) {
    var script = document.createElement('script');
    script.src = 'https://unpkg.com/numjs';

    script.onload = function() {
      window.nj = nj;
    };

    document.body.appendChild(script);
  }
})();
```

**Comment by hajoha** [comment]
Unfortunately, this does not work and it also breaks the Grafana Variables causing them to disappear. Is there a way to load a file from the machine or webserver? I have multiple Plotly graphs that use the same functions but differ only in visualization. Currently, code maintenance is almost impossible.
