### ISSUE TITLE
Export plot as video

### ISSUE THREAD

**Issue by morganchristiansson** [nline/nline-plotlyjs-panel#15]
Hello I have created animated choropleth map, per example on plotly.js https://plotly.com/javascript/map-animations/
Grafana Dashboard is online here: https://intermittency.int.mog.se/d/fa529e06-ff34-415d-adf1-dde1a6f28350/prices-plotly-map?orgId=1

There is a export plot as image button in top right.
But is it possible to export each frame in the animation somehow? Either as separate images that can be combined to animated gif or video or as a video?
Maybe plotly-nline JS function for downloading screenshot can be called from the animation loop?

Also the animation becomes very sluggish for longer timeranges which increases need for video export, but I don't think this is related to your grafana plugin.

Thanks!

**Comment by jacksongoode** [comment]
I think this would be a bit out of scope for this plugin since Plotly doesn't support this feature either. I think you may need to clean up your JavaScript in terms of the performance. You could attempt iterating through the data and triggering the event tied to the `<a>` tag with `data-title="Export plot as an image"` but I would just recommend trying this in. Python if you need that. I would try fetching the json if you're able to.

```js
// Fetch geojson
async function fetchData() {
  if (!window.geojson) {
    try {
      console.log("Fetching!");
      const response = await fetch('https://raw.githubusercontent.com/electricitymaps/electricitymaps-contrib/master/web/geo/world.geojson');
      window.geojson = await response.json();; // Store it in window object
    } catch (error) {
      console.log('Error:', error);
    }
  }
}
fetchData();
geojson = window.geojson;
```

**Comment by morganchristiansson** [comment]
Thanks!
The geojson is modified, removing all shapes outside of Europe increased performance.
I do not have a place for static files atm. It's only loaded once so not an issue, and not too bad to scroll past, but yes should fix.

My code is as clean as the example on plotly, but agree the example is messy. https://plotly.com/javascript/map-animations/

Removing the slider fixed the performance. I posted on plotly forum about it. Anyhow, unrelated to grafana. https://community.plotly.com/t/choropleth-slider-animation-sluggish-with-many-frames/77857

Thanks I will try clicking the <a> element. I thought about using plotly.py or even selenium but I would rather not if possible.
Altho could probably render a super smooth animation with python!

Thanks for advice, much appreciated.
