### ISSUE TITLE
Updating Panel in Editor with working plotly.js code currently not predictable

### ISSUE THREAD

**Issue by allomorphy** [nline/nline-plotlyjs-panel#16]
Hi @jacksongoode and thank you for this nice Grafana Plugin.

Do I understand correctly that this plugin is able to support json code that is honoured by a readably recent version like: https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.33.1/plotly.js ? That would be really great.

I found that we could edit the editor panel of your plugin and could make some changes to the example graph. However pasting a data object that works with plotly.js did not render in the /nline-plotlyjs Panel.

I pasted the data object from a plotly.js working example over the `data` object of the standard example (using the supplied  edit panel). 

What happens? 
There is no error message
The previous working code is reverted when _Apply_ is pressed to the Editor.
So the original visualisation remains in the Grafana panel.

Below is an example of a data object that works in plotly.js but fails as described in this plugin.

I could make some progress with line by line iterative testing, but life is a bit short for that 🤷‍♂️, so I thought to ask how it might be possible to use existing code created in a convenient development environment and then robustly update the code in this nice panel with that working code? If we are not quite there yet, then I understand.

**Thanks for picking Plotly in Grafana up, it is so much needed. 🤗**
We hope that we will still be able to make convenient use of Plotly inside Grafana.

 Warm wishes
 Eric

    { 
              "name": "Working well",
              "text": ['Text A', 'Text B', 'Text C', 'Text D', 'Text E', 'Text F'],
              "fill":"tozeroy", 
              "textposition": 'top',
                 "textfont": {
                   "family": 'sans-serif',
                   "size": 18,
                   "color": '#1f44b4'
               },
              "fillcolor":"rgba(255, 0, 0, 0.3)",

              "type": "scatter",

              "mode": "text+lines+markers",

              "showlegend": true,

                "line": {
                    "color": "blue",
                    "width": 3,
                    "dash": "dashdot",
                    "dashlength": 4,
                    "shape": "spline",
                    "smoothing": 0.6,
                    },

                "marker": {
                   "line": {
                      "width": 8,
                      "color": "yellow"
                   },
                },
           }

**Comment by allomorphy** [comment]
Thank you Jackson for your super fast response. 

1. _Datasource_ :  ✅ Nope that was not an issue for me. It worked out of the box. Loved it. Have since played further with your _Processing Script_ and no issues. (FWIW, we have a plan to upgrade to one of our two Grafana REST api datasources to use with your Plugin).
2. _Version_ : I was using the plotly.js which was only one version behind `2.26` ( actually 2.25.2). I just upgraded to this latest 2.26 and code renders as before with latest version.

My issue remains if it is plug and play as it were from our 2.26 compliant code to your Plugin. Ir are there caveats in element order or other gotchas. I am sure that I can have it working using heuristic methods, but as I said, this is not what I want to spend time doing 😓
Could I take our working json from the plotly.js and paste it into your Panel Editor or directly in the panel (or even dashboard json) and it will work - deterministically?

Since mailing, I managed to have some more features working, but I was hoping that I could cut and paste.
Why no develop directly in your Grafana Plugin Panel?
Because it's much more convenient and efficient to progress the design and develop the code in another very responsive environment which we have.
Another reason is that we want to be able to use our developed Plotly standard code in both Grafana and in other UX implementations.

I am happy to invest time to help this plugin and document issues with code and screenshots as required if that would be useful as _I think that this work is a massive boost for the Grafana community_. The standard Panels like µplot do a lot very well but do not support very many useful d3 features.

So thank you again for this amazing work. And I hope that it will flourish.

Warm wishes
Eric

PS
One small issue that I noticed now is that the global and user variables are interpolating and rendering to the panel graph when added to elements in the `layout` object but not when added to the `data` object.
Example FWIW is:
```
{
  "annotations": [
    {
      "x": 2,
      "y": 10.7,
      "xref": "x",
      "yref": "y",
      "text": "${__user.email} $__interval",
      "textangle": 30,
      "showarrow": true,
      "font": {
        "family": "Courier New, monospace",
        "size": 16,
        "color": "red"
      }
    }
```

**Comment by jacksongoode** [comment]
Yeah your last point about variables not being substituted is a bug I am investigating. I'm not really sure specifically why your existing code wouldn't work. There are no changes made to the actually processing of parameters since standard Plotly.js is being invoked. The `data, layout, config` options are merged into what is added in the `script` section (so `script` will override any of those static configs) and then the Plot is constructed.

**Comment by jacksongoode** [comment]
1.5.2 fixes the variable substitution. Are you experiencing any other specific issues?

**Comment by jacksongoode** [comment]
Just going to close this given that I haven't heard back on any lingering issues identified with the panel itself.
