### ISSUE TITLE
Grafana Panel Refresh Resets Chosen Buttons

### ISSUE THREAD

**Issue by zemorg** [nline/nline-plotlyjs-panel#17]
I am making a panel to display various traces, this panel also receives live data via queries, my issue is that in this panel I have some buttons that alternate between displaying different combinations of the traces, however, when the panel is refreshed by Grafana, the selected button is forgotten and the graph returns to its default state making it necessary to re-click the button every time after a Grafana refresh. 
Is there any way to navigate around this issue, and have the panel remember what buttons have been pressed even with a dashboard refresh?

**Environment**:
- Grafana Version: 10.1.0
- Plotly Plugin Version: 1.5.0

**Comment by jacksongoode** [comment]
Hmm some example code might help, but my guess would be seeing if you are able to set a dashboard variable on button click (set `&var-variable` in the url [see here](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/create-dashboard-url-variables/)). It's an interesting question, but the panel itself doesn't manage user selections beyond the defaults you set - that should be handled by Grafana's systems.

**Comment by zemorg** [comment]
Currently my layout section button definition looks like this:

"updatemenus": [
    {
      "buttons": [
        {
          "args": [
            {
              "visible": [true, true, true, true, true, true, true, true], 
            }
          ],
          "label": "Single and Max",
          "method": "update"
        },

I have created a dashboard variable called Test, and I am able to access its value in the script section of the panel to make changes on the graph like this:

let buttonPressed = variables.Test;

if (buttonPressed == 1){
 //do something here
}

however im not sure how I can make my button change this Test variable to a specific number depending on the button im pression? I'm still new to plotly so maybe this is a very basic question, but I was wondering if you would know how to do it?

**Comment by jacksongoode** [comment]
Hm yeah this is tricky. There's an onclick section, but I suppose if you're creating a button then you would need access to the Grafana functions that let you update the variables there.... [Like here](https://community.grafana.com/t/how-to-update-a-dashboard-variable-from-html-plugin-with-javascript/36222/12) but we only expose those in the on click panel.

**Comment by jacksongoode** [comment]
If you are able to make a public dashboard I could view it might be easier to diagnose how you would do this. @zemorg Have you tried my above suggestion?

**Comment by zemorg** [comment]
Hello, I ended up making the dashboard variable selectable by the user, so this bypassed the need for buttons in the graph that would change it, maybe later I will try the buttons again. Thank you for the quick response, my apologies for taking up your time. I would say its alright to close this issue.

**Comment by jacksongoode** [comment]
Okay great, thanks!
