### ISSUE TITLE
Data editor resets on dashboard refresh

### ISSUE THREAD

**Issue by linush-vk** [nline/nline-plotlyjs-panel#19]
Hey,
I'm facing an issue where the data section of the data editor resets to the default settings (two scatter traces with hoverlabels) when I reload the dashboard containing the Plotly panel. Seems to happen on every Plotly panel I made. On some this behaviour barely changes anything, but on scatter plots of my own it throws of colors, markers.. Either way, I suppose this is not intentional?
We are using Grafana v9.5.3 (916d9793aa).
Besides that, great plugin. Thank you for your work!

**Comment by jacksongoode** [comment]
Hmm, I'll need some more details but are you sure you are saving your changes to the Plotly panel by saving the dashboard itself before you reload? Have you changed the code from the Script editor?

**Comment by linush-vk** [comment]
Yes, I save the dashboard before reloading. No changes in script editor. What's weird is that, when I check the changes after deleting the code in the data panel, it shows them as being newly added to the json (with pluses and green underlay). After saving, the changes are implemented in the dashboard view. After reloading, they are reverted (as in, the code in the data panel returns).

**Comment by jacksongoode** [comment]
Ah, well the data object's default is that code if nothing at all is specified - maybe you have just been removing everything from the data field. If you want it to change you need to specify **something** in the data field like simply
```json
{
    [
        null
    ]
}
```

Or with the YAML options just put:
```yaml
- null
```

**Comment by linush-vk** [comment]
That's what happens, thank you! Yes, I was only processing the data from my SQL request via the script window, defining all the traces there.

I'd suggest either mentioning this behaviour somewhere or outright removing these defaults in the data field - they won't be of any use besides showing first time users how to use the tool I'd think.

**Comment by jacksongoode** [comment]
@linush-vk The forced default examples are removed from new panels now so this shouldn't be an issue anymore.
