### ISSUE TITLE
Increase buffer size of values?

### ISSUE THREAD

**Issue by stanvanrooy** [nline/nline-plotlyjs-panel#2]
Hey! Thank you for making/maintaining this! A lot easier to work with than Grafana's own visualizations IMO.

I do have a question. I am trying to create a scatter plot of requests. This works perfectly, but it seems like I'm only able to plot the last 1000 values. Because of this, I can only look at the latest seconds of logs.

Is it possible to increase the size of the values buffer? Or is there another way to get more values in the plot?

**Comment by jacksongoode** [comment]
Hmm, this might be a Plotly specific issue maybe try `"type": "scattergl"` this should allow you to plot more points.

**Comment by stanvanrooy** [comment]
@jacksongoode, thanks for the reply, but that doesn't seem to change anything for me. 

This is the code I'm using to get the buffer:
![afbeelding](https://user-images.githubusercontent.com/49564025/223090932-da8fd94a-4ecb-4bcc-92fe-28a3900a077c.png)

And this is the output in the console:
![afbeelding](https://user-images.githubusercontent.com/49564025/223091121-4c26c5a7-226b-40fd-9ec5-70f5014f6441.png)

**Comment by jacksongoode** [comment]
Oh I see... huh well this plugin just exposes the data received from your data source query - there are no limits set.

**Comment by jacksongoode** [comment]
Oh I see... huh well this plugin just exposes the data received from your data source query - there are no limits set. Do you see any errors in your web console when this happens?

**Comment by jacksongoode** [comment]
If you inspect your query, how many rows are returned?

**Comment by stanvanrooy** [comment]
It did indeed have nothing to do with the plugin, my bad! In my case, there was a limit on the maximum lines returned by the Loki datasource. Thanks anyway for your help @jacksongoode!
