### ISSUE TITLE
Grafana Dashboard Time Zone into Plotly panel

### ISSUE THREAD

**Issue by alexl04** [nline/nline-plotlyjs-panel#22]
Grafana panels show timestamps including the offset for the chosen dashboard Time Zone. This by default is not the case in Plotly panels if we take the timestamps from query A with data.series[0].fields[0].values for example. Is there a method to do so?

![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/06932b71-49af-4a7b-8bb3-db3e18e475fa)
 
In this example the time in the grafana panel for the water depth is shown correct. The time in the plotly panel is however in my local browser time. All timestamps are stored in UTC.

![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/7df65a29-83c4-47fa-bbf6-c16415fef808)

Awesome plugin btw. We use it a lot

**Comment by jacksongoode** [comment]
Great catch. Yes we've been thinking about this too. Here's one solution. Let me know what you think.

```js
// Assuming x is time series data stored in UTC
let x = data.series[0].fields[0].values;
let y = data.series[0].fields[1].values;

// Where 'offset' is the dashboard timezone string and we assume stored in UTC
const offset = dayjs.utc(x[0]).tz(timeZone).utcOffset() * 60 * 1000;

// Offset all the values
x = x.map(ts => ts - offset);

let trace1 = {
  x: x,
  y: y
};

return { data: [trace1] };
```
I was thinking about doing this with the super minimal dayjs library and pass the dayjs library object and the timeZone variable in to the script context. How does that sound?

**Comment by alexl04** [comment]
> Great catch. Yes we've been thinking about this too. Here's one solution. Let me know what you think. It's a bit hard to assume which column is the time column (since it might have different names and the format of the query returns has to be `Table` form rather than `Time series`). It also might not be the case that the user's data is stored in UTC.
> 
> ```js
> // Assuming x is time series data stored in UTC
> let x = data.series[0].fields[0].values;
> let y = data.series[0].fields[1].values;
> 
> // Where 'offset' is the dashboard timezone string and we assume stored in UTC
> const offset = dayjs().tz(timeZone).utcOffset() * 60 * 1000;
> 
> // Offset all the values
> x = x.map(ts => ts - offset);
> 
> let trace1 = {
>   x: x,
>   y: y
> };
> 
> return { data: [trace1] };
> ```
> 
> I was thinking about doing this with the super minimal dayjs library and pass the dayjs library object and the timeZone variable in to the script context. How does that sound? I was thinking about making some UI around this but I think it might just be better to give a special `matchTimezone()` function that uses the offset, assuming data is stored in UTC, and makes the mapping happen so someone can write.
> 
> ```js
> let x = data.series[0].fields[0].values;
> x = matchTimezone(x);
> 
> let trace1 = {
>   x: x,
>   y: y
> };
> ```

Hi @jacksongoode this looks like a nice fix to me! The code and the library gives full control but I like the function matchTimezone also. Some UI for this will be overkill if you ask me. Documentation is sufficient.

Not sure how Grafana is doing this in their panels but I think the offset has to be checked for every timestamp as the first timestamp of the dashboard time could be winter time and the next summer time.. hence it is best to check all in UTC hmm

**Comment by jacksongoode** [comment]
Great, the latest version (1.6.0) includes both the dayjs library as well as the matchTimezone function. Enjoy!

**Comment by alexl04** [comment]
@jacksongoode sorry for getting back to you but I'm afraid we did oversee the issue. Tried to make it work but I think we need 2 corrections:

1.  time = time_utc.map(ts => ts + offset); // changed - to + 
2. fix this somehow > its seems that the epoch timestamps are once more converted to your local time zone by Plotly if you set the axis type to "date" in the layout section of plotly. To make it simple! arg see below screenshots to make it more clear

![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/2a6cc169-0cbf-4c8a-b0e8-cfa68e064fdc)

![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/a2393f47-459c-41d1-831a-f73febf2c0a6)

![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/210ef02b-1657-488d-aa3d-70a3b2d8e8e5)

and now with axis type "date" in the layout editor
![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/d41097fe-af13-42fe-9734-85c4140a3072)

![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/364fe51c-f098-4b1a-a415-70559ce094fc)
