### ISSUE TITLE
Extremely small text input boxes when editing a panel - nLine Plotly 1.6.1, Grafana v10.2.3

### ISSUE THREAD

**Issue by b-neufeld** [nline/nline-plotlyjs-panel#25]
On the current version of Grafana and Plotly I'm having an issue where all the text boxes (Cross-trace editor, layout, data, etc.) are only 5 pixels high and impossible to resize. 

This happened after my last update a couple weeks ago but I didn't dig into it until now. 

I've disabled all adblocking and extensions and tested on both Chrome and Edge, same result. Other Grafana plugins do not seem to be affected. 

Is this an end-user issue or is anyone else experiencing this? Any more info I can provide? Thanks. 

<img width="484" alt="plotly_issue" src="https://github.com/nline/nline-plotlyjs-panel/assets/18536548/2e38fba8-f1a3-4c44-b7c2-c3287ad7c64c">

**Comment by intermittentnrg** [comment]
Same issue here!

Direct link to reproduce: https://intermittent.energy/d/fa529e06-ff34-415d-adf1-dde1a6f28350/prices-plotly-map?orgId=1&from=now%2Fd&to=now%2B1d%2Fd&var-area=All&var-frame_duration=150&var-scale_max=1000&editPanel=2

**Comment by b-neufeld** [comment]
I can work around this by manually setting the `data-testid="data-testid Code editor container"` element to something larger than 5 pixels, but I'm not quite savvy enough to know if this is the root problem.

**Comment by jacksongoode** [comment]
That's super weird... I don't know what would have caused that. What version of Grafana are you on?

**Comment by jacksongoode** [comment]
@intermittentnrg Ah thank you for the link. This does seem to be something about the new version (10.2). I'll attempt to address this next week!

**Comment by jacksongoode** [comment]
This is fixed the latest version (1.6.5) which you can always install manually.

**Comment by jacksongoode** [comment]
1.6.5 release and this should be resolved! Follow up comments welcome if this doesn't seem resolved.

**Comment by b-neufeld** [comment]
Updated and all is well! 🙏🙏
