### ISSUE TITLE
cannot define number of decimal points when using Inspect -> Data

### ISSUE THREAD

**Issue by abunimeh** [nline/nline-plotlyjs-panel#26]
To reproduce:
- Click on upper right corner three dots
- Inspect -> Data

The number of decimal points is always 1.

Solution:
1- Allow user to remove format so they can see all decimal points
2- Or allow user to define the number of decimal digits to show.

**Comment by jacksongoode** [comment]
I'm not able to reproduce this on my end, could you give a minimal example you're willing to share?

**Comment by jacksongoode** [comment]
@abunimeh Any follow up to this?

**Comment by abunimeh** [comment]
Here are some screenshots 
![image](https://github.com/nline/nline-plotlyjs-panel/assets/8106823/b8ef5998-1a17-405b-80a9-d5a6ec6d8ba9)
![image](https://github.com/nline/nline-plotlyjs-panel/assets/8106823/fe97ff79-82b8-456b-92ab-8ca2649c5459)
<img width="379" alt="image" src="https://github.com/nline/nline-plotlyjs-panel/assets/8106823/a456c17a-0c65-408d-b7ca-79772a2ec476">

the downloaded csv file doesn't contain all decimal points. it only contains whatever is displayed in the inspect pane

**Comment by jacksongoode** [comment]
I think its the Grafana-side that is formatting that data. I would look up this issue from the Grafana repo.

**Comment by jacksongoode** [comment]
Ah this is weird you're right there's no option to toggle off the formatted data.

**Comment by abunimeh** [comment]
If I don’t use the plotly plugin, I can change the format settings

**Comment by jacksongoode** [comment]
I'll keep looking into this... sorry about that. You might just want to duplicate the data into a Table viz, reuse the same query, and then download it that way unformatted.

**Comment by jacksongoode** [comment]
I believe this now works, at least I am able to see the formatted data toggle on the Inspect: Panel > Data view

**Comment by abunimeh** [comment]
I will try v1.6.7 and report back.

**Comment by abunimeh** [comment]
v1.6.7 LGTM. Thanks!
