### ISSUE TITLE
Rotating a 3D plot causes flickering and changes in data visibility

### ISSUE THREAD

**Issue by positron96** [nline/nline-plotlyjs-panel#28]
Hi. I am trying to plot a series of scatter3d lines (one per timestamp), and when I rotate the plot interactively, it flickers heavily and  random points from the data are dropped, sometimes to the point that only a small portion of the plot is shown, and sometimes, there is no data at all. Is it a known problem? 

Here are some screenshots when rotating the plot (the first one shows all of the data, and next are lost)

![image](https://github.com/nline/nline-plotlyjs-panel/assets/2095278/6681f589-1bcb-4136-9770-70edc3d1088e)

![image](https://github.com/nline/nline-plotlyjs-panel/assets/2095278/f9b66ee9-24c7-4aae-8368-046251cf2968)

![image](https://github.com/nline/nline-plotlyjs-panel/assets/2095278/f9b91efa-b1c5-44bb-adbf-fa09bf6e8322)

![image](https://github.com/nline/nline-plotlyjs-panel/assets/2095278/8367b311-1731-433e-a1ac-7279a266c082)

**Comment by jacksongoode** [comment]
Could you make a minimal example of this and I would be happy to investigate. My first thought is maybe that you have some values for the view of the 3d model set in the config.

**Comment by positron96** [comment]
Hi! No, I left the configs as default, only added zero margin to layout YAML.
Anyway, while making a minimal example I discovered that this flickering only happens when you take data from a histogram (I have a prometheus datasource with "metric_bucket" metric, with labels le=1000, le=2000,...,le=39000,le=+Inf). 

Here is a minimal example ("Processing script", all other sections are default, except `margin: {b: 0, l: 0, r: 0, t: 0}` added to `layout`):
```
let times = data.series[0].fields[0].values.map((t)=>new Date(t));
let values = data.series[0].fields[1].values;
lines = []
const N = 30
for(let i=0; i<times.length; i++) {
  let line = { 
    y: Array.from({length: N}, (_, n) => n),
    x: Array.from({length: N}, (_, n) => times[i]),  
    z: Array.from({length: N}, (_, n) => values[i]),
    type: 'scatter3d', 
    mode: 'lines'
  };
  lines.add(line)
}

return { 
  data: lines,
  layout: {
    showlegend: false,
  }
};
```

For every timestamp it creates a line of 30 points with value from 1st series, so it works with ordinary queries for, e.g. cpu temperature. And it does not flicker with these queries. But the moment you select a "something_bucket" metric, it starts flickering and missing data when you rotate the plot.
![image](https://github.com/nline/nline-plotlyjs-panel/assets/2095278/357f4ba1-0360-41fe-83b9-6dbe72f3fbb1)
This is how the script works for a temperature metric. Yes, it's not pretty and not very usable, but it's a minimal example.

But if you choose a "something_bucket" metric with structure described above, and rotate the plot, at some points it can look like this: 
![image](https://github.com/nline/nline-plotlyjs-panel/assets/2095278/d7ad4c13-595a-4e95-908e-1e3de89a2659)

Also you can notice that not only plot data gets distorted, but also axes and grids and axes tick labels.

**Comment by positron96** [comment]
Well, it's an upstream issue: 
https://github.com/plotly/plotly.js/issues/3306
https://github.com/plotly/plotly.js/issues/6505

supposedly, the fix is in this PR: https://github.com/gl-vis/gl-axes3d/pull/23

**Comment by positron96** [comment]
The PR has not been approved in 3 years, but anyway this project is not the right place to fix this bug, so closing, yes. Thanks!
