### ISSUE TITLE
YAML Layout editor is reformatted every time it looses focus

### ISSUE THREAD

**Issue by positron96** [nline/nline-plotlyjs-panel#29]
It seems that every time Layout editor looses focus, its contents are parsed and formatted again as a YAML document and put into Layout editor. It means your formatting will be lost. 
In particular, if you comment something out, the comment will be immediately erased when you leave the editor.
If you put something as a JSON-style inline value (e.g. `[1,2,3]` or `{a:b, c:d}`), it is immediately reformatted as multiline value.

While this is not critical, it is rather inconvenient.

**Comment by jacksongoode** [comment]
Yeah, I'm aware of this bug, it's rendered to make sure its proper JSON before executing. We should probably save a copy that's unaltered and keep it there.

**Comment by jacksongoode** [comment]
This is fixed in 1.7.0!
