### ISSUE TITLE
Grafana dashboard crashes as soon as there is a critical error in the script

### ISSUE THREAD

**Issue by alexl04** [nline/nline-plotlyjs-panel#30]
Grafana 10.4
Latest nline version

When there is an issue in the script because of some missing data for example the dashboard crashes imminently. With Grafana 10.0 and latest nline version the dashboard did not crash and we received a nice error message in the plotly panel showing what you did wrong in the script.

Hope it can be brought back as debugging becomes almost impossible now. Not sure what Grafana changed on their side.

![image](https://github.com/nline/nline-plotlyjs-panel/assets/56631466/52aecddb-c6cc-4c3e-ab71-0521c5fee239)

**Comment by jacksongoode** [comment]
Thank you, this will be fixed in the latest version rolling out today.

**Comment by alexl04** [comment]
Thanks!
