### ISSUE TITLE
Possible bug: opening parenthesis in the panel

### ISSUE THREAD

**Issue by frederic-schmaljohann** [nline/nline-plotlyjs-panel#32]
Hello,

when using version 1.6.6 there is an opening parenthesis rendered in the panel. Grafana version is 10.1.6.

Best regards

Screenshot:

<img width="906" alt="image" src="https://github.com/nline/nline-plotlyjs-panel/assets/1277406/9aa62b2b-28d2-4fc9-9f37-eecb8d678266">

**Comment by alexl04** [comment]
Same in Grafana 10.4.1 🫣

**Comment by jacksongoode** [comment]
Oh jeez, thanks for telling me. I'll fix this quickly!

**Comment by jacksongoode** [comment]
Fixed in 1.6.7 and the Grafana team will be publishing to the marketplace by today hopefully.

**Comment by jacksongoode** [comment]
Published on the marketplace!
