### ISSUE TITLE
Marker symbols besides circle throw error: "Image could not be loaded"

### ISSUE THREAD

**Issue by YellowDog3629** [nline/nline-plotlyjs-panel#33]
This is related to a closed issue:
https://github.com/nline/nline-plotlyjs-panel/issues/31

The issue was closed as a CORS problem but that is not the problem. If you look at the CORS error, it was related to loading from "localhost:8000" which was a map tile server. I have removed that code from the example.

https://yellowdog3629.grafana.net/public-dashboards/377337337f4743db85a24fefe2bea7f6

The error in the console is this:
![image](https://github.com/nline/nline-plotlyjs-panel/assets/124449827/8efa669e-9ea0-436d-ba02-fc2c4739c2e7)

**Comment by YellowDog3629** [comment]
As you can see in the grafana dashboard linked in the question, the icon is NOW displaying.

The solution to fix the issues was two changes:
1. In the layout, the "style" property of mapbox was set to "basic"
2. Added the property "accesstoken" to the mapbox.  The token doesn't really matter but it does need to be listed. For the token, you just make a free account on mapbox.com and generate a public token

customLayout = {
  "dragmode": "zoom",
  "mapbox": {
    "bearing": 0,
    "center": {
      "lat": 42.459332,
      "lon": -97.266983
    },
    **"accesstoken": token,
    "style": "basic",**
    "zoom": 8
  },
  "margin": {
    "b": 0,
    "l": 0,
    "r": 0,
    "t": 0
  }
}

**Comment by jacksongoode** [comment]
Thank you for commenting with the solution! I hadn't seen a need for the style set to basic!

**Comment by YellowDog3629** [comment]
I have been looking for many months on and off to get the symbols to display on my map! Figured it might someday help someone else.

One comment about the airport image is you can see it is a bit "blurry". Once scaled up to be larger, it loses resolution. Also, you can't change the color. 

Solution I found to make things more prominent was to render TWO items at the same location. 

First insert the item for the "airport" (or whatever icon) into the array of objects to be rendered.  This is set to "marker" and the "allowoverlap" property must be set to true.

Second item inserted into the array with the _same_ lat/lon is "marker+text". Here use a "circle" which you can resize nicely, set color, etc. and add an identifier like a node id for the text. Again, "allowoverlap" must be set to true.
