### ISSUE TITLE
bar chart  does not show categories axis

### ISSUE THREAD

**Issue by grafra** [nline/nline-plotlyjs-panel#34]
I am trying to use the plugin in grafana 9.2.1  with an mysql data source.

In the end I will generate a  floating bar chart  showing the data from the data source.

But as fist step I tried to show one sample bar chart from the plotly site

My code looked like this

Yes I now the first two lines are not used right now, but I kept them for later.

```
let x = data.series[0].fields[0].values.buffer;
let y = data.series[0].fields[1].values.buffer;
let trace =   {
    x: ['giraffes', 'orangutans', 'monkeys'],
    y: [20, 14, 23],
    type: 'bar'
  }

return { data: [trace] }
```

The chart  has got the correct values for the y-axis but the x-axis does not show any of the three categories and the bars.

![plotly-nline](https://github.com/nline/nline-plotlyjs-panel/assets/5072893/e19640d6-7614-4eb3-9213-9935653acdb9)

**Comment by jacksongoode** [comment]
@grafra Hi, if you look at the "Layout" section above, you will see that changing the default:
```
xaxis:
  type: date
```

to 

```
xaxis:
  type: category
```

Will resolve your issue.

**Comment by grafra** [comment]
OK, thanks this in deed solved the problem.
However I would never come to this solution on my own.
The documentation is quite slim

**Comment by jacksongoode** [comment]
@grafra https://plotly.com/javascript/reference/ Here is the reference documentation for all of Plotly's figures.
