### ISSUE TITLE
Grafana 11.1 - Dashboard Crash if error in JS

### ISSUE THREAD

**Issue by alexl04** [nline/nline-plotlyjs-panel#38]
Hi it looks like something changed in grafana again causing the plotly panel to crash the dashboard as soon as there is an error/typo in the script. Some time ago you fixed it for grafana 10 by showing the error message for line x in the panel. Hope this is possible for grafana 11 also. Running the latest version of your plugin

<img width="318" alt="image" src="https://github.com/nline/nline-plotlyjs-panel/assets/56631466/6d92f789-86dd-4d9c-9bf0-d5a6f23df6f1">

**Comment by jacksongoode** [comment]
Ugh, I'll look into this again. The error handling for panels is quite odd and annoying.

**Comment by alexl04** [comment]
I can imagine! The boring part also I assume but I might have good news! After deleting my browser cache etc I did not encounter any issues during debugging JS scripts in the panel anymore. If there is an error or j the script now the error message is like before showing inside the panel and the browser does not crash (chrome).

**Comment by jacksongoode** [comment]
I think there is much better error handling in 2.0 so I'll close this hoping it doesn't return :)
