### ISSUE TITLE
Adding event listeners

### ISSUE THREAD

**Issue by ArianitZ** [nline/nline-plotlyjs-panel#4]
Is there any way of adding event listeners to the panel?
A simple use-case is the ability to highlight a point/line/bar when hovering over it. In order to achieve this you need to be able to add event listeners for hover and unhover events to the graph div component. I've yet to find out how to do this. Is this not supported as of now?

**Comment by jacksongoode** [comment]
Thanks for the suggestion. I suppose it would be possible if you did the scripting either in the `script` field. However, it might make sense to add an additional field that would serve to allow these kind of additional scripted events to be plugged in.

**Comment by SoftwareExplorer1** [comment]
I have tried adding Event Listeners using oninitialized but it doesn't work, my use case is to add click event for axis labels, wanted to click on each label to update Grafana variables

**Comment by jacksongoode** [comment]
I've added the `click`, `zoom` and `relayout` handlers which be present in 1.8.0. I can add more if they work!
