### ISSUE TITLE
Globals are not present in `variables`

### ISSUE THREAD

**Issue by stevenpaligo** [nline/nline-plotlyjs-panel#40]
Using Grafana 11.1.3 and plugin version 1.7, the `variables` variable does not include the globals (`__from`, `__to`, etc.). It only includes the custom dashboard variables that I created.

**Comment by jacksongoode** [comment]
<img width="552" alt="image" src="https://github.com/user-attachments/assets/d6ce3c73-44ab-4d6c-b837-83e339cac831">


I think `variables.__from` and others should be included there?

**Comment by jacksongoode** [comment]
@stevenpaligo Could you confirm this and check the full suite of properties on the `variables` var by `console.log(variables);` from the Script section.

**Comment by stevenpaligo** [comment]
@jacksongoode I put `console.log(variables);` in the panel's Processing Script section. This is all that was logged:

![image](https://github.com/user-attachments/assets/fd9ec40f-49e5-427d-a31b-aade5814d8c9)

Those are the custom dashboard variables I created.

**Comment by jacksongoode** [comment]
Ah indeed, there is an issue. Thanks, I'll fix it!

**Comment by jacksongoode** [comment]
This will be fixed in the next release.
