### ISSUE TITLE
Set TimeRange/TimeTicker based-off selected plotly range 

### ISSUE THREAD

**Issue by nharper-usgs** [nline/nline-plotlyjs-panel#41]
Hi!

I was wondering if it'd be possible to implement the ability for a graph (or at least a 2d cartesian graph) to set the time range for the entire dashboard (via the timeticker) by selecting and dragging a time range on the plotly panel. 

This would be similar to how all of the default/built-in panels currently update the time ranges for all the displayed panels.

**Comment by jacksongoode** [comment]
Just whipped up an example. We needed to make more of the Plotly events available.
For this, each Plot has a toggle that determines whether it would change the dashboard range.


https://github.com/user-attachments/assets/bf129326-f969-4f4b-b78d-c4e3a07d9e6f
<img width="350" alt="image" src="https://github.com/user-attachments/assets/eb33ae47-74f8-4f40-abbd-7b0c097e30c1">

**Comment by nharper-usgs** [comment]
Yes! This is amazing. I'd done some crazy logic with event handlers in the initialized script, but it required a page refresh. I was literally grabbing the new Xs from the plotly_relayout event and refreshing the page url with new from/to variables.

**Comment by jacksongoode** [comment]
So this is in 1.8.0 but there might be some bugs around this so I'll leave the issue open for now.
