### ISSUE TITLE
Configure Tooltip

### ISSUE THREAD

**Issue by CptOrange16** [nline/nline-plotlyjs-panel#44]
How can i configure the hover tooltip that shows up when i hover over my panels?
![imagem](https://github.com/user-attachments/assets/7ab9698a-e2c6-4a2c-b519-fe24a6d0ddb5)

I would like to change both the background colors and the layout of the text inside the tooltip.

I have read this plotly [wiki](https://plotly.com/javascript/hover-text-and-formatting/) and I see that there is an option  called a hover template that has the behaviour i'm looking for.
Where could i configure this in the panel?

**Comment by jacksongoode** [comment]
Please read through the readme for more helpful instructions. If you see on that page, the `hovertemplate` is defined in the `data` object that gets passed in so you need to pass it in either in the script or data sections where `hovertemplate` is a prop in the trace.

```js
data = [{... hovertemplate: `Your template text: ${variable}` }].
```

**Comment by CptOrange16** [comment]
Just an update
I looked more into plotly and apparently the hover template does not work for plots of box type, which is the one i have.
I'll have to look for an alternative plugin as i do need a boxplot graph

Thanks for the help
