### ISSUE TITLE
Reusing functions within scripts

### ISSUE THREAD

**Issue by zzv2** [nline/nline-plotlyjs-panel#45]
This is more of a question or feature request than an issue, but I have many long javascript functions within plotly panel scripts that are duplicated between panels, is there any way to easily reuse code and avoid duplication? Maybe hosting some javascript file that can be imported, or some way to add to the built in plotly plugin functions like `matchTimezone`?

**Comment by jacksongoode** [comment]
You can use the global `window` variable and assign the functions as properties like `window.your_fn = your_fn` after you've defined it. Then it can be used once it is declared anywhere on the page.
