### ISSUE TITLE
release v1.8.0 not available on grafana.com?

### ISSUE THREAD

**Issue by aq-daniel** [nline/nline-plotlyjs-panel#46]
Hello,
the new release v1.8.0 seems to be not available on the official grafana plugin page [grafana.com](https://grafana.com/grafana/plugins/nline-plotlyjs-panel/)?

**Comment by jacksongoode** [comment]
I'm still going through the publishing process, there needed to be some migration scripts since I simplified the way we pass in contextual variables.
