### ISSUE TITLE
Table not plotted in v1.8

### ISSUE THREAD

**Issue by alexl04** [nline/nline-plotlyjs-panel#49]
Hi, I just noticed that tables are not plotted anymore in v1.8.

When the below test script is plotted we receive message: No data No trace found with data.

const testTable = {
  type: 'table',
  header: {
    values: ['Test Header'],
    align: 'center',
    line: { width: 1, color: 'black' },
    fill: { color: 'grey' },
    font: { family: 'Arial', size: 14, color: 'white' }
  },
  cells: {
    values: [['Test Data']],
    align: 'center',
    line: { color: 'black', width: 1 },
    font: { family: 'Arial', size: 14, color: ['black'] }
  }
};

return { data: [testTable] };

**Comment by jacksongoode** [comment]
Yeah I just noticed this bug unfortunately. I've added a fix in 1.8.1.

**Comment by jacksongoode** [comment]
This should be fixed with 1.8.1 which has been released.
