### ISSUE TITLE
Map does not render when using a local (offline) tile server and mapbox layers

### ISSUE THREAD

**Issue by YellowDog3629** [nline/nline-plotlyjs-panel#5]
I have an "offline" or local map tile server that I am trying to use with the mapbox layers but the map does not render in the panel.
In the "Layout" section I have added a layers item within the mapbox, set the style to white-bg, and added a below traces item per the plotly js instructions. Specifically: 
```
"mapbox": {
    "layers": [
      {
        "below": "traces",
        "source": [ "http://localhost:8080/{z}/{x}/{y}.png"],
        "sourcetype": "vector"
      }
    ],
    "style": "white-bg",
  }
```

I can connect to the tile server in my browser and see the tiles but the panel never renders them and instead is just solid white.

**Comment by jacksongoode** [comment]
I would guess this is some CORS issue... I doubt it is specifically an issue with Plotly or this plugin specifically.

**Comment by YellowDog3629** [comment]
This is exactly what it turned out to be! For others that come here to solve this issue, I ended up installed a CORS blocking extension to my browser and that fixes the issue. For example, for FireFox, I used CORS Everywhere and whitelisted the source IP/port that was querying for the map tiles.

**Comment by jacksongoode** [comment]
Great I'll close the issue!

**Comment by yosiasz** [comment]
@YellowDog3629 can you please share you script?

**Comment by YellowDog3629** [comment]
It was not a script issue. It was CORS blocking the map being rendered. I installed a CORS extension in the browser and set it to allow the url of the map server.
