### ISSUE TITLE
Dashboard variables' "All" option is not interpolated

### ISSUE THREAD

**Issue by hafeja** [nline/nline-plotlyjs-panel#7]
Hi, nice plugin 👍!

As plugin user I want to access a dashboard variable's "All" value from within `Script` section:
![image](https://github.com/nline/nline-plotlyjs-panel/assets/59864250/834a4fc1-b6e9-42fe-9668-ae8598efc7ac)
![image](https://github.com/nline/nline-plotlyjs-panel/assets/59864250/7b7ef99a-5c7c-4ecf-9fb8-e987078d4e0f)

**Expected behavior**
Variable `xtip` is updated. The new variale value is a **list of all values** of dashboard variable `xAxis`. Example: If dashboard variable `xAxis` has options "1", "2" and "test", the content of `xtip` is `[1, 2, "test"]`

**Actual behavior**
New value of the updated variable `xtip` is "All" instead of a list of actual values.

How to access the **list of values** from a dashboard variable's "All" option from within the Script section?

Looking forward for feedback 😊

**Comment by jacksongoode** [comment]
Yeah this seems to be due to the `text` prop getting accessed. I'll look at this for the next release!

**Comment by jacksongoode** [comment]
Just to follow up @hafeja @MarcoPignati @kklement, you can get a list of the variables selected by "All" by accessing the variable in a different format than the default, like `${variable:type} where type can be `csv`, `json`, `value` or others.

Please see Grafana's [documentation on variable formats](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/) they should all work in the current version.

<img width="944" alt="image" src="https://github.com/nline/nline-plotlyjs-panel/assets/54308792/3a8026c7-120c-4748-b1d2-ec1d48112279">
