### ISSUE TITLE
Dashboard variables are not handed off correctly for repeated panels

### ISSUE THREAD

**Issue by danellis10** [nline/nline-plotlyjs-panel#8]
Grafana allows you to mark a panel as "repeated" based on selections in a variable.  If you a variable called Server with values of server1, server2, server3, etc., the panel gets dynamically repeated, one for each variable value.  This works great in Grafana itself and if you include "Server: $server" in the title field for the panel, each dynamically created panel will have the correct title (Server: server1, Server:server2,... ). 

The plug-in doesn't seem to support this and each dynamically created panel will have the complete variable selection (if you selected all three servers, each panel will have variables.server equal to ['server1', 'server2', 'server3'] and each panel will will have same data set.

Is there a way to have variables.server only reflect the intended value for repeated panels?

See below, the title is correct (grafana passes the variable correctly), but the data set is still all three servers.  Is there a workaround for this or could the plugin be updated to only set variables.server to the single instance for repeated panels?

![image](https://github.com/nline/nline-plotlyjs-panel/assets/107132024/bcb00eab-5d71-4304-a4f2-b9cb20381f93)

**Comment by danellis10** [comment]
![image](https://github.com/nline/nline-plotlyjs-panel/assets/107132024/927c17ca-e947-49fd-be4d-05b7b65e5d8d)

**Comment by jacksongoode** [comment]
Thanks for making this issue! This was fixed in 1.4.0 and is currently awaiting approval from the Grafana team.

**Comment by danellis10** [comment]
I think this will fall under the category of user-error.  I was able to reproduce the behavior in the stock panels and figured out the issue I was doing in the configuration (I had a filter wrong).

**Comment by jacksongoode** [comment]
I think you might have to break up the array. You can inspect the `variables` object in the Script section and apply the layout you want there. The yaml/json fields are intended to be static for the most part (though you can use Grafana variables there inplace).

**Comment by jacksongoode** [comment]
Can you confirm you were able to solve this?

**Comment by danellis10** [comment]
Not in an elegant way.

I have my Datasource A which has all my data in a CSV file (infinity
plugin).
I have a Dashboard variable called ID which is multi-value ([15,16] in this
case).  When each panel gets rendered, each panel sees the variable.ID as
[15,16], so the script can't view variables.ID to determine which instance
it is.  There is one panel for 15 and one panel for 16.
Since I need data for both 15 and 16, I can't directly filter the
datasource A to only 15 or 16.

The one workaround I found is to create a Datasource B that sets a value to
15 or 16 respectfully.  In infinity datasource, this was done through a CSV
Inline data source where I create an inline CSV with a single column of
PanelID  for the headers and a single data row of $ID.  This gets made
visible into the script as data.series[1].fields[0].values.buffer[0].

Inside the script, I can iterate over all the data and perform special
actions based on what repeated panel it is.

It would be very nice to have the repeated panel instance and the
untouched dashboard variable available to the script and not just at the
grafana filter/datasource level.  I am on Grafana 8.3.

Thanks,
Dan

**Comment by jacksongoode** [comment]
Ah, is it possible for you to upgrade Grafana? I wouldn't be able to test your use case given all the changes that have been made since then - 8 is quite old.

**Comment by danellis10** [comment]
Hi, this is still an issue with Grafana 11.  At its essence, for a repeated plotly panel, I have no ability within the plotly script to determine which instance of the repeated variable panel I'm in.  If I have a dashboard variable call server with A and B values, and choose a plotly panel to repeat on the server variable, I correctly get two repeated panels, but the script has "variable.server" variable set to both repeated instances, but no other means to distinguish the "instance" of the panel.  There should be a means from within the script to get both the full selection (which is what its doing today) and the instance.

![image](https://github.com/user-attachments/assets/f981f508-cb59-4847-a37a-2ed9593da9fa)

**Comment by jacksongoode** [comment]
Hmm, I think could be a bit out of scope for the panel itself.

Is this not what you're after?

https://github.com/user-attachments/assets/c8bed925-773b-4f0b-9c79-0d2da9d95a54

**Comment by jacksongoode** [comment]
Yeah this is tricky. I have a fix for it in the next patch! I'll add a `replaceVariables` function that picks up the scope.


https://github.com/user-attachments/assets/d4ec6107-e8b5-41a3-8559-8b2200fd5d22

**Comment by jacksongoode** [comment]
@danellis10 Please try the `utils.replaceVariables($variable)` included in 1.8.1.
